services:
  backend:
    build:
      args:
        TORCH_INDEX_URL: https://download.pytorch.org/whl/cu124
    environment:
      DEVICE: cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
